- docker-compose.prod.yml
Removed limit on number of restarts as not allowed by unless-stopped policy
> Updating restart policy to "unless-stopped" in prod

- docker/prod/Dockerfile
- src/ENS/ens.service.ts
These changes were in place temporarily for deployment of PR #46
> Reverting changes which clear DB on startup.

- src/application/application.service.ts
- src/organization/organization.service.ts
Adding extra comment to help future understanding of changes made in PR #46 
@dwojno Let me know what you think of the comments.
> Comments re check for array in "others" uid mapping

- src/ENS/ens.service.ts
- src/application/application.service.ts
- src/claim/claim.service.ts
- src/owner/owner.service.ts
- src/role/role.service.ts
I've added the subOrgs to the get orgs by owner endpoint.
Also added some fixes regarding not removing subOrgs while ENS sync
> feat(owner): return subOrgs from org owner endpoint

- package-lock.json
- package.json
- src/auth/login.controller.ts
https://medium.com/@arcagarwal/same-site-changes-in-chrome-1c86973454f9
> fix(cookies): samesite none cookie issue

- src/modules/role/role.service.ts
Same fix that was made here: https://github.com/energywebfoundation/iam-client-lib/commit/560f85a801a889469f430b34e91576cff2735202
> fix(role.service): check for empty conditions array

- src/modules/assets/assets.controller.ts
https://sentry.io/organizations/energy-web/issues/2323842027/?project=5651522
> fix(assets.controller.getByID): check for null asset

- src/modules/assets/assets.subscriber.ts
Reverts energywebfoundation/iam-cache-server#108
> Revert "bug/asset transfer events are not published"

- package-lock.json
- package.json
- src/modules/ens/ens.service.ts
> fix(ens.service): fix import of DomainNotifier from iam-contracts

- README.md
- docker/dev/Dockerfile
WIP to improve iam-cache-server dev instructions. Let me know what you think
> docs: update dev setup in readme

- src/migrations/1622548828009-AddClaimRegistrationTypes.ts
- src/migrations/1622630172870-AddClaimSubjectAgreement.ts
- src/migrations/1622631478371-AddClaimOnChainRoleProof.ts
- src/modules/claim/claim.entity.ts
- src/modules/claim/claim.types.ts
> feature/SWTCH-906 register on-chain claim request

- src/modules/claim/claim.service.ts
https://energyweb.atlassian.net/browse/SWTCH-984
A commit with checking of owned and offered assets didn't included in "claims of subjects" PR
> bug/SWTCH-984 can't get subjects claims

- src/modules/claim/claim.dto.spec.ts
- src/modules/claim/claim.dto.ts
SWTCH-1061
Adding subjectAgreement to claim.dto so that it gets persisted to the entity
> fix(claim.dto): add subjectAgreement+registrationTypes

- src/migrations/1628527857091-dropClaimIssuerColumn.ts
- src/modules/claim/claim.dto.spec.ts
- src/modules/claim/claim.dto.ts
- src/modules/claim/claim.entity.ts
- src/modules/claim/claim.types.ts
- src/scripts/migrate.ts
> Removes claimsIssuer from Claims

- src/modules/claim/claim.service.ts
> Fix queryFailedError relating to missing ClaimIssuer column

- .github/workflows/cache_server.test.yml
- src/modules/claim/claim.service.ts
- src/modules/claim/claims.controller.e2e.spec.ts
- src/modules/nats/nats.service.ts
https://energyweb.atlassian.net/jira/software/projects/ICS/boards/86?selectedIssue=ICS-43
Additionally 
- closed Nats connection on Nats module destroy, because it is prevents jest from exit
- configure redis for CI
> bug/ICS-43 can't get subject claims

- src/modules/ens/ens.service.ts
Pass proper node hash to event handler from `NewOwner` ENS event.
> fix(ens): fix ENS event listeners

- src/modules/did/did.service.ts
Add a new checking if the value is BigNumber during log parsing
> fix(did.service): fix parse parse logs

- src/modules/did/did.service.spec.ts
- src/modules/did/did.service.ts
Test is checking if service supports current implementation of `BigNumber` from `ethers` library.
> test(did.service): check parsing BigNumbers

- src/modules/claim/claim.controller.ts
- src/modules/claim/claim.service.ts
Link to task: https://energyweb.atlassian.net/browse/ICS-86
> feat(roles): retrieve roles by issuer ICS-86

- src/modules/claim/claim.service.ts
Motivation: https://docs.nats.io/using-nats/developer/receiving/queues
> feat(nats): use queues for processing nats messages

- .github/workflows/build_and_deploy.yml
Should fix https://github.com/energywebfoundation/iam-cache-server/runs/4394610370?check_suite_focus=true
> ci: set argocd action to fixed version

- docs/api/README.md
- docs/api/enums/modules_claim_claim_types.ClaimEventType.md
- docs/api/modules/modules_claim_claim_types.md
- src/modules/claim/claim.controller.ts
- src/modules/claim/claim.types.ts
url field not in use anymore due to the fact we are fetchin claims through iam-client-lib now
> feat(nats): removed unnecessary fields from messages

- src/modules/claim/claim.service.ts
on chain claim issuance does not need issuedToken present
> fix(claims) issue claim on-chain without issuedToken

- package-lock.json
- package.json
- src/modules/logger/logger.service.ts
redacting every logged message to strip it from sensitive data
> feat(logs): striping sensitive data from logs

- package-lock.json
- package.json
- src/modules/logger/logger.service.ts
logs are now being sent to file and console on every env
> feat(logs): enable logs in console to display in argo

- package-lock.json
- package.json
- src/modules/auth/refreshToken.repository.ts
- test/auth/refreshToken.testSuite.ts
https://energyweb.atlassian.net/browse/ICS-143
> bug/ICS-143 expired refresh token isn't deleted

- src/modules/claim/claim.controller.ts
Only issuer signature for issuedToken needs to be verified. Remove wrong implementation for onChainProof verification.
> fix(claim): only verify issuer signature for issueToken

- src/modules/claim/claim.service.ts
rename claim to previouslyRequestedClaim to make its purpose clear
> refactor(handleClaimIssuanceRequest): rename for readability

- package-lock.json
- package.json
Reverts energywebfoundation/ssi-hub#335
`/login` endpoint is not functioning
```
[Nest] 1  - 02/15/2022, 3:49:49 PM   ERROR [ExceptionsHandler] Invalid DID
94
Error: Invalid DID
93
at getDIDChain (/app/node_modules/@ew-did-registry/did/dist/utils/parser.js:29:15)
```
> Revert "build(deps): update `passport-did-auth`"

- docker/prod/Dockerfile
Update node image version to 16.10.0 in prod Dockerfile.
Fix for https://github.com/energywebfoundation/ssi-hub/runs/5991093982?check_suite_focus=true
> ci: update node version

- package-lock.json
- package.json
- src/modules/ens/ens.service.unit.spec.ts
Merges fix from @energyweb/credential-governance
> bug/EC-36 can't read role without credentials

- docs/api/classes/modules_status_list_status_list_controller.StatusListController.md
- src/modules/status-list/status-list.controller.ts
Problem with the proxies that we have.
> fix: get hostname from env instead of request object

- docs/api/classes/modules_claim_claim_handle_result_dto.ClaimHandleResult.md
- src/modules/claim/claim-handle-result.dto.ts
- src/modules/claim/claim.controller.ts
- src/modules/claim/services/claim-issuance.service.ts
- src/modules/claim/services/claim.service.ts
Reverts energywebfoundation/ssi-hub#421
> Revert "fix: claim issuance nats id broadcast"

- README.md
Looking to trigger an authentication failure
No actual changes are made
> chore: testing file-issuer authentication

- docs/api/classes/modules_claim_resolvers_credential_resolver.RoleCredentialResolver.md
- docs/api/classes/modules_claim_services_revocation_verification_service.RevocationVerificationService.md
- docs/api/classes/modules_did_did_service.DIDService.md
- docs/api/classes/modules_status_list_status_list_controller.StatusListController.md
- docs/api/modules.md
- docs/api/modules/common_url_decode_decorator.md
- src/main.ts
Had introduced to test Argo notifications
> chore: remove Error on startup

- CHANGELOG.md
- package-lock.json
- package.json
Updating CHANGELOG and package.json versions for v2.9.0
New PR from https://github.com/energywebfoundation/ssi-hub/pull/462 to add IPFS changes
> 2dot9 release 3

- src/modules/did/did.controller.ts
- add logging for DID document retrieval
> chore: add logging for DID document retrieval

- src/modules/assets/assets.controller.ts
- Adding in this param so I can test this endpoint on Swagger. Currently swagger does not allow id input for this endpoint.
> fix: add nestJS API param for asset DID

- docs/status-list.md
Adding documentation on `status-list` design
https://github.com/energywebfoundation/ssi-hub/blob/status-list-documentation/docs/status-list.md
> docs(status-list): add module readme

- devops/dev/Chart.yaml
- devops/prod/Chart.yaml
- devops/sandbox/Chart.yaml
- devops/staging/Chart.yaml
Upgrade helm chart version to use newest HPA API
> chore(helm): upgrade helm versions

- CHANGELOG.md
- package-lock.json
- package.json
Adding changelog and updating version for 2.11 release
> 2.11 release

- CHANGELOG.md
- package-lock.json
- package.json
Adding release notes for 2.11.1
> chore(release): 2.11.1

- src/modules/did/did.processor.ts
This PR:
- adds application error log messages for failed processing of queued jobs
- handles claims pinning errors by writing an application error log message
> feat: adding log messages

- src/modules/role/role.dto.ts
Incorrectly committed yesterday for #554
> fix(role.dto): schema is object, not date

- docs/api/classes/modules_auth_cookies_service.CookiesServices.md
- src/modules/auth/cookies.service.ts
- src/modules/auth/login.controller.ts
This PR removes chrome browser specific validation and cookies update
> fix: remove chrome specific cookies update

- .github/workflows/build-deploy.yml
The PR adopts GHCR while dropping ECR for the ssi-hub images.
It also updates the image repository used in the ArgoCD deployments for ssi-hub.
> feat: switch from ecr to gchr

- .github/workflows/build-deploy.yml
- devops/dev/values.yaml
- devops/prod/values.yaml
- devops/sandbox/values.yaml
- devops/staging/values.yaml
also removing unique_id generation as it isn't used anymore
> build(build-deploy): replace unique_id with IMAGE_TAG

- devops/dev/values.yaml
- devops/prod/values.yaml
- devops/sandbox/values.yaml
- devops/staging/values.yaml
failures noticed in dev and staging
this is attempt to address
> build(values): increase requested memory

- src/modules/did/did.processor.ts
This fixes recently occurred `Error pinning claims Unexpected token o in JSON at position 1` bugs
> Claims of updated document are not pinned

- docs/api/classes/modules_did_did_processor.DIDProcessor.md
- docs/api/classes/modules_ipfs_pin_processor.PinProcessor.md
- src/modules/did/did.processor.ts
- src/modules/did/did.service.ts
- src/modules/ipfs/ipfs.service.ts
- src/modules/ipfs/pin.processor.ts
Handles errors on adding pin and DID synchronization jobs
> Exceeded DID queue memory limit

- docs/api/classes/modules_ipfs_pin_processor.PinProcessor.md
- package-lock.json
- package.json
Should be no functional change as was already updated by passport-did-auth update
> feat(deps): update vc-verification version

- .github/workflows/build-deploy.yml
- devops/dev/Chart.yaml
- devops/dev/values.yaml
- devops/staging/values.yaml
- docs/api/classes/modules_auth_login_strategy.AuthStrategy.md
- docs/api/classes/modules_did_did_processor.DIDProcessor.md
- docs/api/classes/modules_did_did_service.DIDService.md
- docs/api/classes/modules_ipfs_ipfs_service.IPFSService.md
- docs/api/classes/modules_ipfs_pin_processor.PinProcessor.md
- docs/api/modules/modules_ipfs_ipfs_types.md
- package-lock.json
- package.json
- src/modules/claim/resolvers/credential.resolver.ts
- src/modules/did/did.processor.ts
- src/modules/did/did.service.ts
- src/modules/ipfs/ipfs.service.ts
- src/modules/ipfs/ipfs.types.ts
- src/modules/ipfs/pin.processor.ts
- src/setup-swagger.function.ts
Merging into the `release` branch to generate a v2.14.0 release. This release has the IPFS request timeout fix.
> v2.14 Release
