energywebfoundation/ssi-hub

- deploy.sh
- makefile
As @jrhender pointed out we have an `access denied` error while removing old db dumps running in CI/CD.
So I was thinking that this is not a bad idea ;) we shouldn't be able to remove that important data while using CI/CD. We still have a cron job that is doing that every 12 hours, so I've added a script to backup db without removing it from the server in CI/CD env
> [MYEN-524] remove posibility to delete anything through CI/CD

- src/did/did.controller.ts
See https://energyweb.atlassian.net/browse/MYEN-534 for context on this bug.
This change is a quick fix for the issue. If going with it, it might make sense to retrieve & return the DID Doc instead of returning 404 if not cached.
A better solution would be to fix with Dgraph transactions, possibly with an upsert query.
https://dgraph.io/docs/clients/overview/#transactions
https://dgraph.io/docs/howto/upserts/
> Awaiting refresh of didDoc cache to avoid duplication

- src/claim/claim.service.ts
- src/dgraph/dgraph.service.ts
- src/did/did.service.ts
- test/app.e2e-spec.ts
The addition of  `"esModuleInterop": true` means that we should import CommonJS modules in compliance with es6 modules spec. This is currently causing bug in where full claims are not returned when retrieving DID Document.
> Changing CommonJS imports to ES Module syntax

- src/did/DidTypes.ts
- src/did/did.controller.ts
- On GET retrieving DID Doc after caching so that clients (e.g. iam-client-lib) doesn't have to
- Adding additional validation&normalization on address component of DID
> fix(did caching): improving DID Document retrieval

- src/auth/login.controller.ts
- src/claim/claim.controller.ts
- src/claim/claim.service.ts
Only logged user which is a requester for certain not accepted and not rejected claim can cancel it.
> feat(auth): protect deleting endpoint

- README.md
@JGiter @marcin-l-tsh What do you think about adding this tip on the cookie policy when running in dev. I've found it handy. Have you found a different way to get the cookies to work while doing local development?
> docs: add note about cookie policy when using localhost

- src/modules/role/role.service.ts
Same fix that was made here: https://github.com/energywebfoundation/iam-client-lib/commit/560f85a801a889469f430b34e91576cff2735202
Fix was already made to `develop` but needs to be pushed to `master` https://github.com/energywebfoundation/iam-cache-server/commit/1d446d3de10422ec1f660d3209d5c2876589d61c#diff-25a6634263c1b1f6fc4697a04e2b9904ea4b042a89af59dc93ec1f5d44848a26
Partially fixes: https://energyweb.atlassian.net/browse/SWTCH-982
> fix(role.service): check for empty conditions array

- src/modules/application/application.controller.spec.ts
- src/modules/application/application.service.spec.ts
- src/modules/claim/claim.controller.spec.ts
- src/modules/claim/claim.dto.spec.ts
- src/modules/claim/claim.dto.ts
- src/modules/claim/claim.service.spec.ts
- src/modules/did/did.controller.spec.ts
- src/modules/did/did.service.spec.ts
- src/modules/ens/ens.service.spec.ts
- src/modules/nats/nats.service.spec.ts
- src/modules/organization/organization.controller.spec.ts
- src/modules/organization/organization.service.spec.ts
- src/modules/role/role.controller.spec.ts
- src/modules/role/role.service.spec.ts
- src/modules/search/search.controller.spec.ts
- src/modules/search/search.service.spec.ts
iam-client-lib is submitting versions as numbers so convert to string until we migrate `claimTypeVersion` column.
Also disabled failing tests so that `npm run test` passes (still need to run on ci build, should be done by https://energyweb.atlassian.net/browse/SWTCH-840 )
> Bug/swtch 982/fix enrolment

- package-lock.json
- package.json
ENS Sync can now handle deleted namespace
https://energyweb.atlassian.net/browse/SWTCH-997
> fix: update iam-contracts to fix ENS Sync

- src/modules/did/did.service.spec.ts
- src/modules/did/did.service.ts
https://energyweb.atlassian.net/browse/SWTCH-1043
> SWTCH-1043 only return IDIDDocument

- src/modules/ens/ens.service.ts
ensRegistry events can be for domains using different resolver contracts
e.g. legacy role definitions on PublicResolver and new defs on RoleDefResolver
So need to use domainReader to handle this
> fix(ens.service): domainReader for registry events

- src/modules/auth/token.service.spec.ts
- src/modules/auth/token.service.ts
Change internal server error to unauthorized error when `Origin` header not matched with origin stored in JWT payload.
> feat(auth): change error when origins not matched

- src/modules/ens/ens.service.ts
- src/modules/ens/ens.service.unit.spec.ts
Filter out roles and apps domains in ENS event handler and avoid reading their empty metadata.
> fix(ens): avoid read metadata from `roles` and `apps` domains

- src/modules/did/did.module.ts
- src/modules/did/did.service.spec.ts
- src/modules/did/did.service.ts
Use HttpModule and HttpService from @nest/axios instead of @nest/common because of deprecation.
> refactor(HttpModule): use HttpModule from @nest/axios

- .github/workflows/cache_server.test.yml
Disabling commitlint to merge into master
Likely commitlint was added after some of the fault commit were added
Need to fix old commits or fix commitlint command, then reenable
> chore: disable commitlint

- package-lock.json
- package.json
- src/modules/claim/claim.controller.ts
- src/modules/nats/nats.service.spec.ts
- src/modules/nats/nats.service.ts
remove duplicated DIDs , fixed problem with wrong subject in case of issuedToken not present
> fix(claims): ensure only one event is propagated to each notified DID

- src/modules/nats/nats.service.spec.ts
A `jest` `only` was accidentally added in PR #250
> test(nats.service): remove "only"

- .github/workflows/cache_server.test.yml
It was disabled because we had old commits
which didn't pass commitlint which we had to merge into master
But now all commit should be conform to conventional commit
> build: renable commitlint

- .github/renovate.json
Since we've change base branch to `develop` we don't need to override this option anymore
> chore(renovate): remove base branch option

- docker-compose.dev.yml
Must have been a typo. Not sure why they would be there at all
> fix(docker-compose.dev): remove backticks

- src/modules/assets/assets.service.ts
The problem was that `at` is a built-in function for arrays in node 16 (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at#browser_compatibility) so it's shadow out property in parsed logs. We have only one BigNumber object in parsed logs which is our old `at` value, so that's why this fix looks like this.
> fix(assets): fix parsing assets logs

- src/modules/role/role.service.ts
`role` is the previous object in database and `data` is the new definition. It always save old definition during update.
> fix: updating roles definition

- devops/staging/values.yaml
Pods failing in staging could be a resource issue
This is intended to remove limits to check this
> chore(staging values): align resources with dev

- devops/dev/values.yaml
- devops/prod/values.yaml
- devops/staging/values.yaml
Need to update the memory limit due to didkit-wasm-node usage https://github.com/spruceid/didkit/issues/301
Also increase CPU utilization target slightly based on Grafana usage graphs
Also aligning `dev`, `staging` and `prod` to have the same values so that we can observed issues in `dev` and `staging` prior to production
> chore: update memory and cpu limits

- devops/dev/values.yaml
- devops/prod/values.yaml
- devops/staging/values.yaml
Reverts energywebfoundation/ssi-hub#444
These limits aren't sufficient to avoid the pod startup issues
> Revert "chore: update memory and cpu limits"

- src/modules/assets/assets.controller.ts
- src/modules/assets/assets.service.ts
- The DID pipe was sending ID and stripping away the chain info ('did'ethr...'). 
- (0xEa242C31FCcB83Aa1Bf3b29e4B4b276E85024aa8 from did:ethr:volta:0xEa242C31FCcB83Aa1Bf3b29e4B4b276E85024aa8)
- Asset IDs are saved in the database in this format, so it wasn't finding any records. 
ASSET_TRANSFERRED event for did:ethr:volta:0x921*** saved: {\**"assetId\":\"did:ethr:volta:0x921*****\",\"at\":PHONE_NUMBER,\"emittedBy\":\"did:ethr:volta:0x06B***\",\"timestamp\":\"DIGITS-08-19T13:37:50.000Z\",\"relatedTo\":\"did:ethr:volta:0x17b***\",\"type\":\"ASSET_TRANSFERRED\",\"id\":DIGITS}\n"
> fix: send asset id as did to DID pipe

- src/modules/assets/assets.service.ts
- For bug https://energyweb.atlassian.net/browse/SWTCH-1424 
- Converts addresses to DIDs before inserting into Asset DB
- Addresses the following error thrown in SSI hub:
2022-08-29 07:47:07 | {"log":"This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:\n","stream":"stderr","time":"2022-08-29T11:47:07.573531931Z"}
-- | --
| 2022-08-29 07:47:06 | {"log":"    at processTimers (node:internal/timers:500:7)\n","stream":"stderr","time":"2022-08-29T11:47:06.007813164Z"}
| 2022-08-29 07:47:06 | {"log":"    at listOnTimeout (node:internal/timers:557:17)\n","stream":"stderr","time":"2022-08-29T11:47:06.007810093Z"}
| 2022-08-29 07:47:06 | {"log":"    at …
> fix: convert addresses to DIDs before inserting to DB

- docs/api/classes/modules_status_list_status_list_service.StatusListService.md
- src/modules/status-list/status-list.service.spec.ts
- src/modules/status-list/status-list.service.ts
- verifyRevoker in ew-credentials throws several different errors. SSI Hub does not handle the reason at all, so there is no way of knowing why the verifyRevoker failed. This adds a catch so the logger can log the error description. I would add that we should add the reason to the throw message as well, but that is up for debate. At the very least, we can log the error.
> fix: log revoker error for debugging

- tsconfig.build.json
Having hardhat config in dist forces typescript include src/ directory in dist, which leads to inability to resolve main.js, which is expected to be in root of dist
> remove hardhat config from dist

- src/modules/claim/resolvers/credential.resolver.ts
- src/modules/did/did.service.ts
Fix for bug https://energyweb.atlassian.net/jira/software/projects/SWTCH/boards/54?assignee=608057a2e3b59800688dbc2a&selectedIssue=SWTCH-1539
Fixes 2 issues:
1. Uses arrow in chained methods in order to preserve "this" context (fixes issue of cannot read 'ipfs' of undefined or this)
2. Formats token so it can be passed to isEIP191Jwt method. Previously was not formatted and so no claims were coming back from the check, and therefore the pre-requisite role was never found for verifier
Regression testing performed:
1. Can revoke on-chain credential for role-based revoker
2. Can revoke off-chain credential for did-based revoker
3. Can revoke on-chain credential for did-based revoker
**I'm thinking we won't want to merge this till after demo tomorrow, just in case, even if approved**
> #swtch 1539 revoke by role

- src/main.ts
This PR solves the issue when running SSI HUB locally and enabling authorization with `ENABLE_AUTH` in the `.env` file has no effect.
> fix: fixing ENABLE_AUTH having no effect when set in .env file

- src/modules/auth/login.controller.ts
This PR fixes /auth/status endpoint is not marked with a padlock icon in the Swagger doc.
> fix: fixing /auth/status endpoint swagger definition 

- .env.dev
- .github/workflows/build-test.yml
- docker-compose.dev.yml
- docs/api/modules.md
- docs/api/modules/env_vars_validation_schema.md
- e2e/app.e2e.spec.ts
- src/app.module.ts
- src/env-vars-validation-schema.ts
This PR:
- adds validations for env variables so that all required needs to be provided and all are validated formally
- adds a requirement that all env vars accessed with the ConfigService need to be defined in the [validation schema](https://github.com/energywebfoundation/ssi-hub/blob/feat/configuration-validation/src/env-vars-validation-schema.ts), otherwise they are stripped out
TODO:
> feat: configuration validation

- src/env-vars-validation-schema.ts
- src/modules/assets/assets.service.ts
- src/modules/auth/token.service.ts
- src/modules/did/did.processor.ts
- src/modules/did/did.service.ts
- src/modules/ens/ens.service.ts
After environment variables validation schema values returned by the configuration service are cast to appropriate types, so configuration variables of type boolean or number need to be handled accordingly. This was skipped by mistake when implementing the validation schema.
> fix: env vars handling

- docs/api/classes/modules_role_role_dto.FieldsDTO.md
- src/modules/role/role.dto.ts
I tested locally that `schema` is returned from a role that issuerField/requestorField with it:
> feat(role.dto): add optional schema prop

- devops/prod/Chart.yaml
This reverts commit d8af92fddd422cdf11cdc7e29ee01d3a1880c9c5.
The objective of this PR is to revert the commit that caused the merge conflict that is preventing the ssi-hub v2.12 release to prod PR from being merged: https://github.com/energywebfoundation/ssi-hub/pull/576
> Revert "fix: bump chart"

- .github/workflows/build-deploy.yml
`{{ github.sha }}` provides correct hash
See https://github.com/energywebfoundation/ssi-hub/actions/runs/4204185001/jobs/7294512989 for test
> build(build-deploy.yml): use github.sha

- docker/prod/Dockerfile
Reverts energywebfoundation/ssi-hub#603 as this caused failing build here: https://github.com/energywebfoundation/ssi-hub/actions/runs/4415762210/jobs/7739162339
> Revert "build(Dockerfile): node 16.19.1 for security fixes"

- devops/prod/values.yaml
- devops/staging/values.yaml
This PR fixes the issue with requests sent from the Swagger interface are forbidden server-side
> chore: adding gp4btc swagger hostnames to allowed origins 

- .github/workflows/build-deploy.yml
- docker-compose.full.yml
- docker/prod/Dockerfile
- docs/api/modules.md
- docs/api/modules/setup_swagger_function.md
- src/main.ts
- src/setup-swagger.function.ts
This PR adds the application build version displayed by the Swagger document with:
- injecting GIT_SHA arg into the docker image when built in CI
- storing build info in the `build.json` file inside the docker image
- adding the `package.json` file to the docker image
- getting the version from the `package.json` file
- parsing `build.json` and displaying git sha and build timestamp next to the version in Swagger
- handling cases of not present or non-parseable files
> feat: git sha in dockerimage

- .github/workflows/build-deploy.yml
Looks like quotation marks break json created in the Dokerfile: https://github.com/energywebfoundation/ssi-hub/blob/340f022c44b6178b547fb650b545cd378e1818d5/docker/prod/Dockerfile#L33
> fix(CD): fixing non-parseable `build.json` file

- src/common/cors.config.ts
This should simplify local development by setting `ALLOWED_CORS_ORIGIN` to `http://localhost:4200`. Currently this url is not allowed, because `isUrl` validator [here](https://github.com/energywebfoundation/ssi-hub/blob/c2b949ee46532ea59665d694f134df23b1721051/src/common/cors.config.ts#L9) by default requires top level domain
> chore: allow CORS from origin without top level domain

- devops/dev/values.yaml
The `dev` environment is facing memory issues, this PR increases the memory to handle the spike. This is a temp fix.
> build(values): increase memory for dev

- docs/api/classes/modules_did_did_processor.DIDProcessor.md
- docs/api/classes/modules_did_pin_processor.PinProcessor.md
- docs/api/modules.md
- docs/api/modules/modules_did_did_types.md
- docs/api/modules/modules_did_pin_processor.md
- src/modules/did/did.module.ts
- src/modules/did/did.processor.ts
- src/modules/did/did.service.spec.ts
- src/modules/did/did.service.ts
- src/modules/did/did.types.ts
- src/modules/did/pin.processor.ts
Trying to handle two issues:
- stalled pinning to cluster blocks synchronization of document, because pinning is part of synchronization job. Now jobs are separate
- stalled synchronization job block other jobs. ~~Now jobs will be ran in separate processes~~. Unfortunatelly this forces to give up nestjs injection https://docs.nestjs.com/techniques/queues#separate-processes. Instead pinning jobs are added in another queue. This way pinning will not block synchronization, but jobs in the same queue can still block each other
Also refactored debug logs from handlers
Locally tested that this is fixes publishing issue
> SWTCH-2439 claim not synced

- .github/workflows/build-deploy.yml
- devops/staging/values.yaml
This PR:
- Uses released ssi-hub image for deploy to staging (i.e. `master` branch)
- Removes build of new image when merging to `master`. We can put this back later if staging env is disconnected from `master` branch in the future
@Timtech4u adding you as reviewer as you helped setup the ssi-hub build for gp4btc so you might remember something about this area
> Feat/swtch 2493/no master build

- docs/api/classes/modules_did_did_processor.DIDProcessor.md
- docs/api/classes/modules_ipfs_ipfs_service.IPFSService.md
- docs/api/classes/modules_ipfs_pin_processor.PinProcessor.md
- docs/api/modules/modules_ipfs_ipfs_types.md
- src/modules/did/did.processor.ts
- src/modules/ipfs/ipfs.service.ts
- src/modules/ipfs/ipfs.types.ts
- src/modules/ipfs/pin.processor.ts
Fix for `Waiting undefined claim undefined` error 
The reason of the error is that in did.processor data for pin job [it is an object](https://github.com/energywebfoundation/ssi-hub/blob/80855fdd2f60da65d1d6b87c54603e6a2c48704c/src/modules/did/did.processor.ts#L66), while pin.processor [expect a string](https://github.com/energywebfoundation/ssi-hub/blob/80855fdd2f60da65d1d6b87c54603e6a2c48704c/src/modules/ipfs/pin.processor.ts#L53). The fix is to specify type of data
> Undefined pin job

- docs/api/classes/modules_assets_assets_service.AssetsService.md
- src/modules/logger/logger.service.ts
With digits redactor, the logs looked like:
debug [DIDService] : 2024-11-21T22:32:25.999Z - Fetched 0 DID events from interval [DIGITS, DIGITS]
> fix(logger.service): disable digits redactor

- package-lock.json
- package.json
The new version has an updated vc-verification package that includes a timeout when resolving IPFS data. This is useful in the data where IPFS data can't be resolved. We recently observed this for Infura hosted data that was added via the public gateway.
> feat(deps): update passport-did-auth to 2.1.0-alpha.1

- src/modules/ipfs/pin.processor.ts
* Fixing types or arguments passed to job callbacks
* Logging IPFS request errors
> Handle pin claim job errors

- devops/staging/values.yaml
This version allows login despire failed queries to IPFS. The version tag can be verified here: https://github.com/energywebfoundation/ssi-hub/pkgs/container/ssi-hub/versions
Will update with proper released version once the fix is published.
> chore(staging values): update app version with ipfs timeout fix

- docs/api/classes/modules_ipfs_pin_processor.PinProcessor.md
- src/env-vars-validation-schema.ts
- src/modules/did/did.processor.ts
Adds configuration to disable IPFS cluster pinning. As EW isn't hosting the IPFS cluster, the pinning always fails which makes logs much harder to read.
> Feat make cluster pinning configurable

- devops/staging/values.yaml
No functional change; just numbered release.
Will be easier to troubleshoot AEMO issues in the future if staging is running a numbered release as it's easier to refer to the numbered release.
> chore(staging values): update to v2.14.0
